### ISSUE TITLE
change the smtp port

### ISSUE THREAD

**Issue by dtrckd** [tiredofit/docker-postal#4]
Good evening,

How can we change the smtp port of the expose container ? 
I set it to `25:2525` in the docker-compose file but doesn't seem to work. 

I see that the network ports are also defined in the DockerFile so maybe its hardcoded ?

**Comment by tiredofit** [comment]
Try`SMTP_SERVER_PORT` as en environment variable.

Defaults are [here](https://github.com/tiredofit/docker-postal/blob/master/install/assets/defaults/10-postal). Looks like I haven't kept the README up to date for a while, my apologies.

**Comment by dtrckd** [comment]
thanks @tiredofit.
I just try that: `SMTP_SERVER_PORT=2525 docker-compose up -d` but the app/config/postal.yml file  still have SMTP port at 25.
Is that the right way to proceed ?

**Comment by tiredofit** [comment]
Yes, that should just work, provided you have not switched `SETUP_TYPE=MANUAL` 

This is a snippet of the config that I write:

````
smtp_server:
  port: ${SMTP_SERVER_PORT}
  tls_enabled: ${SMTP_SERVER_ENABLE_TLS}
  tls_certificate_path: ${SMTP_SERVER_TLS_CERT}
  tls_private_key_path: ${SMTP_SERVER_TLS_KEY}
  tls_ciphers: ${SMTP_SERVER_TLS_CIPHERS}
  ssl_version: ${SMTP_SERVER_SSL_VERSION}
  proxy_protocol: ${SMTP_SERVER_PROXY_PROTOCOL}
  log_connect: ${SMTP_SERVER_LOG_CONNECTIONS}
  strip_received_headers: ${SMTP_SERVER_STRIP_RECEIVED_HEADERS}
  max_message_size: ${SMTP_SERVER_MAX_MESSAGE_SIZE}
````
